// Моковые данные для демо-версии
export const mockApartments = [
  {
    id: '1',
    title: 'Панорамная студия в Москва-Сити',
    slug: 'panoramic-studio-moscow-city',
    description: 'Роскошная студия с видом на небоскрёбы Москва-Сити. Панорамные окна, современный дизайн, премиум техника.',
    pricePerNight: 8500,
    location: 'Москва-Сити, башня ОКО',
    tower: 'oko',
    rooms: 1,
    bathrooms: 1,
    area: 45,
    floor: 25,
    maxGuests: 2,
    capacity: 2,
    amenities: ['Wi-Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'ТВ', 'Панорамный вид'],
    images: [
      { url: '/apartments/apartment-001.jpg', alt: 'Панорамная студия' },
      { url: '/apartments/apartment-002.png', alt: 'Вид из окна' },
      { url: '/apartments/apartment-003.png', alt: 'Спальная зона' },
    ],
    featured: true,
    available: true,
  },
  {
    id: '2',
    title: 'Двухкомнатные апартаменты на Пресне',
    slug: 'two-room-presnya',
    description: 'Просторные апартаменты в самом сердце делового центра. Две спальни, большая гостиная, полностью оборудованная кухня.',
    pricePerNight: 12000,
    location: 'Пресненская набережная',
    tower: 'neva-t1',
    rooms: 2,
    bathrooms: 2,
    area: 75,
    floor: 18,
    maxGuests: 4,
    capacity: 4,
    amenities: ['Wi-Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'ТВ', 'Парковка', 'Джакузи'],
    images: [
      { url: '/apartments/apartment-007.jpg', alt: 'Двухкомнатные апартаменты' },
      { url: '/apartments/apartment-008.jpg', alt: 'Гостиная' },
      { url: '/apartments/apartment-009.jpg', alt: 'Спальня' },
    ],
    featured: true,
    available: true,
  },
  {
    id: '3',
    title: 'Уютная студия у метро',
    slug: 'cozy-studio-metro',
    description: 'Компактная и уютная студия в 5 минутах от метро. Идеально для одного или пары. Всё необходимое для комфортного проживания.',
    pricePerNight: 4500,
    location: 'Деловой центр',
    tower: 'oko',
    rooms: 1,
    bathrooms: 1,
    area: 30,
    floor: 12,
    maxGuests: 2,
    capacity: 2,
    amenities: ['Wi-Fi', 'Кондиционер', 'Кухня', 'ТВ'],
    images: [
      { url: '/apartments/apartment-010.jpg', alt: 'Уютная студия' },
      { url: '/apartments/apartment-011.jpg', alt: 'Кухонная зона' },
      { url: '/apartments/apartment-012.jpg', alt: 'Ванная' },
    ],
    featured: false,
    available: true,
  },
  {
    id: '4',
    title: 'Премиум-пентхаус в небоскрёбе',
    slug: 'premium-penthouse',
    description: 'Эксклюзивный пентхаус на последнем этаже с террасой и видом на весь город. Три спальни, дизайнерский ремонт, умный дом.',
    pricePerNight: 25000,
    location: 'Москва-Сити, башня Федерация',
    tower: 'neva-t2',
    rooms: 3,
    bathrooms: 3,
    area: 150,
    floor: 45,
    maxGuests: 6,
    capacity: 6,
    amenities: ['Wi-Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'ТВ', 'Парковка', 'Терраса', 'Консьерж', 'Сауна'],
    images: [
      { url: '/apartments/apartment-013.jpg', alt: 'Премиум-пентхаус' },
      { url: '/apartments/apartment-014.jpg', alt: 'Гостиная с видом' },
      { url: '/apartments/apartment-015.jpg', alt: 'Главная спальня' },
      { url: '/apartments/apartment-016.jpg', alt: 'Терраса' },
    ],
    featured: true,
    available: true,
  },
  {
    id: '5',
    title: 'Семейные апартаменты с 3 спальнями',
    slug: 'family-three-bedroom',
    description: 'Идеальные апартаменты для семьи или большой компании. Три изолированные спальни, просторная кухня-гостиная.',
    pricePerNight: 15000,
    location: 'Пресненская набережная',
    tower: 'neva-t1',
    rooms: 3,
    bathrooms: 2,
    area: 95,
    floor: 22,
    maxGuests: 6,
    capacity: 6,
    amenities: ['Wi-Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'ТВ', 'Парковка', 'Детская кроватка'],
    images: [
      { url: '/apartments/apartment-017.jpg', alt: 'Семейные апартаменты' },
      { url: '/apartments/apartment-018.jpg', alt: 'Кухня-гостиная' },
      { url: '/apartments/apartment-019.jpg', alt: 'Детская комната' },
    ],
    featured: true,
    available: true,
  },
  {
    id: '6',
    title: 'Бизнес-студия для командировок',
    slug: 'business-studio',
    description: 'Функциональная студия для деловых поездок. Рабочая зона, высокоскоростной интернет, близко к бизнес-центрам.',
    pricePerNight: 6000,
    location: 'Деловой центр',
    tower: 'oko',
    rooms: 1,
    bathrooms: 1,
    area: 40,
    floor: 15,
    maxGuests: 2,
    capacity: 2,
    amenities: ['Wi-Fi', 'Кондиционер', 'Кухня', 'ТВ', 'Рабочий стол', 'Принтер'],
    images: [
      { url: '/apartments/apartment-020.jpg', alt: 'Бизнес-студия' },
      { url: '/apartments/apartment-021.jpg', alt: 'Рабочая зона' },
    ],
    featured: false,
    available: true,
  },
  {
    id: '7',
    title: 'Романтические апартаменты с видом',
    slug: 'romantic-view',
    description: 'Стильные апартаменты для романтического отдыха. Панорамные окна, джакузи, приглушённое освещение.',
    pricePerNight: 10000,
    location: 'Москва-Сити',
    tower: 'oko',
    rooms: 1,
    bathrooms: 1,
    area: 50,
    floor: 28,
    maxGuests: 2,
    capacity: 2,
    amenities: ['Wi-Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'ТВ', 'Джакузи', 'Панорамный вид'],
    images: [
      { url: '/apartments/apartment-022.jpg', alt: 'Романтические апартаменты' },
      { url: '/apartments/apartment-023.jpg', alt: 'Спальня' },
      { url: '/apartments/apartment-024.jpg', alt: 'Ванная с джакузи' },
    ],
    featured: false,
    available: true,
  },
  {
    id: '8',
    title: 'Лофт с высокими потолками',
    slug: 'high-ceiling-loft',
    description: 'Дизайнерский лофт с потолками 4 метра. Индустриальный стиль, панорамные окна, открытая планировка.',
    pricePerNight: 14000,
    location: 'Пресненская набережная',
    tower: 'neva-t2',
    rooms: 2,
    bathrooms: 1,
    area: 80,
    floor: 20,
    maxGuests: 4,
    capacity: 4,
    amenities: ['Wi-Fi', 'Кондиционер', 'Кухня', 'Стиральная машина', 'ТВ', 'Парковка'],
    images: [
      { url: '/apartments/apartment-025.jpg', alt: 'Лофт' },
      { url: '/apartments/apartment-026.jpg', alt: 'Гостиная' },
      { url: '/apartments/apartment-027.jpg', alt: 'Кухня' },
    ],
    featured: false,
    available: true,
  },
]

export interface MockApartment {
  id: string
  title: string
  slug: string
  description: string
  pricePerNight: number
  location: string
  tower: string
  rooms: number
  bathrooms: number
  area: number
  floor: number
  maxGuests: number
  capacity: number
  amenities: string[]
  images: { url: string; alt: string }[]
  featured: boolean
  available: boolean
}
